var y=Object.defineProperty;var L=(s,e,t)=>e in s?y(s,e,{enumerable:!0,configurable:!0,writable:!0,value:t}):s[e]=t;var n=(s,e,t)=>(L(s,typeof e!="symbol"?e+"":e,t),t);import{a as I,i as u,S as P}from"./assets/vendor-b42c18af.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))c(r);new MutationObserver(r=>{for(const a of r)if(a.type==="childList")for(const m of a.addedNodes)m.tagName==="LINK"&&m.rel==="modulepreload"&&c(m)}).observe(document,{childList:!0,subtree:!0});function t(r){const a={};return r.integrity&&(a.integrity=r.integrity),r.referrerPolicy&&(a.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?a.credentials="include":r.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function c(r){if(r.ep)return;r.ep=!0;const a=t(r);fetch(r.href,a)}})();class w{constructor(e){n(this,"BASE_URL","https://pixabay.com/api/");n(this,"currentPage",1);n(this,"resultsPerPage",15);n(this,"totalPages",0);n(this,"query","");this.apiKey=e}async getImageList(){const e={params:{key:this.apiKey,q:this.query,image_type:"photo",orientation:"horizontal",safesearch:"true",page:this.currentPage,per_page:this.resultsPerPage}};try{const t=await I.get(this.BASE_URL,e);return this.totalPages=Math.ceil(t.data.totalHits/15),t.data.hits}catch{throw new Error("something went wrong")}}}function f(s){return s.length<=0?(u.error({message:"Sorry, there are no images matching your search query. Please try again!",progressBar:!1,transitionIn:"fadeIn",position:"topRight"}),"no images found"):s.map(t=>`<li class="gallery-item">
            <a class="gallery-link" href="${t.largeImageURL}">
              <img src="${t.webformatURL}" alt="${t.tags}" width="360" height="200">
            </a>
            <ul class="gallery-item-desc">
              <li class="gallery-item-desc-item"><span class="gallery-item-desc-cap">Likes</span><span>${t.likes}</span></li>
              <li class="gallery-item-desc-item"><span class="gallery-item-desc-cap">Views</span><span>${t.views}</span></li>
              <li class="gallery-item-desc-item"><span class="gallery-item-desc-cap">Comments</span><span>${t.comments}</span></li>
              <li class="gallery-item-desc-item"><span class="gallery-item-desc-cap">Downloads</span><span>${t.downloads}</span></li>
            </ul>
          </li>`).join("")}function p(s,e){e.insertAdjacentHTML("beforeend",s)}const d=document.querySelector(".gallery-list"),b=document.querySelector(".search-form-input"),q=document.querySelector(".search-form"),g=document.querySelector(".loader"),l=document.querySelector(".load-more-button"),S="42304499-2f6eff4512ca2196326987647",i=new w(S),h=new P(".gallery-list a",{captionDelay:250,captionsData:"alt"});async function v(s){if(s.preventDefault(),d.innerHTML="",i.currentPage=1,i.query=b.value,o(l,!1),R(i.query)){o(g,!0);const e=await i.getImageList();if(o(g,!1),e.length>0){const t=f(e);p(t,d),h.refresh(),i.totalPages>1&&o(l,!0)}else u.info({message:"No images found",progressBar:!1,transitionIn:"fadeIn",position:"topRight"})}else u.error({message:"Search attribute is not valid",progressBar:!1,transitionIn:"fadeIn",position:"topRight"})}async function B(s){s.preventDefault(),i.currentPage+=1,o(g,!0),o(l,!1);const e=await i.getImageList();o(g,!1);const t=f(e);p(t,d),h.refresh();const c=document.querySelector(".gallery-item");window.scrollBy({top:c.getBoundingClientRect().height*2,behavior:"smooth"}),i.totalPages===i.currentPage?(o(l,!1),u.info({message:"We're sorry, but you've reached the end of search results.",progressBar:!1,transitionIn:"fadeIn",position:"topRight"})):o(l,!0)}function R(s){return s.trim()!==""}function o(s,e=!1){e?s.classList.remove("hidden"):s.classList.add("hidden")}q.addEventListener("submit",v);l.addEventListener("click",B);
//# sourceMappingURL=commonHelpers.js.map
